## Exercises for Students

Perform row and column operations to reduce the following matrices to an upper triangular form and calculate their determinants by taking the product of the diagonal elements.

### 1. Matrix \( A \):
\[
A = \begin{bmatrix}
12 & 3 \\
-18 & -4
\end{bmatrix}
\]

### 2. Matrix \( B \):
\[
B = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\]


In [1]:
import numpy as np

# Matrix A
A = np.array([[12, 3],
              [-18, -4]])

# Row operations to reduce A to upper triangular form
A[1] = A[1] + (A[1][0] / A[0][0]) * A[0]

# Determinant of A by the product of diagonal elements
det_A = np.prod(np.diag(A))

print("Matrix A after row operations (upper triangular form):")
print(A)
print(f"Determinant of A: {det_A}")

# Matrix B
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Row operations to reduce B to upper triangular form
B[1] = B[1] - 4 * B[0]  # R2 = R2 - 4*R1
B[2] = B[2] - 7 * B[0]  # R3 = R3 - 7*R1
B[2] = B[2] - (B[2][1] / B[1][1]) * B[1]  # Eliminate R3,2 element

# Determinant of B by the product of diagonal elements
det_B = np.prod(np.diag(B))

print("\nMatrix B after row operations (upper triangular form):")
print(B)
print(f"Determinant of B: {det_B}")


Matrix A after row operations (upper triangular form):
[[ 12   3]
 [-36  -8]]
Determinant of A: -96

Matrix B after row operations (upper triangular form):
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]
Determinant of B: 0
