# Exercise: Matrix Inversion using Gauss-Jordan Elimination

## Problem Statement

In this exercise, you will find the inverses of the following matrices using the **Gauss-Jordan elimination method**. The Gauss-Jordan method involves augmenting the matrix with the identity matrix and applying row operations to transform the original matrix into the identity matrix. The result on the right side of the augmented matrix will be the inverse.

### Matrices:

1. **Matrix A**:
$$
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

2. **Matrix B**:
$$
B =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 1 \\
2 & 3 & 2
\end{bmatrix}
$$

3. **Matrix C**:
$$
C =
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
$$

### Steps for Gauss-Jordan Elimination:

1. **Augment the matrix**: Create an augmented matrix by appending the identity matrix to the right of the given matrix.
   
2. **Row operations**:
    - Swap rows if needed to make sure the pivot element is non-zero.
    - Scale rows to make pivot elements equal to 1.
    - Subtract rows from one another to eliminate all elements below and above the pivot.
   
3. **Check for Inversibility**: If the matrix cannot be reduced to the identity matrix through row operations, it does not have an inverse (i.e., it is singular).

4. **Output the result**: Once the matrix is in reduced row echelon form, the matrix on the right will be the inverse of the original matrix.

### Your Task:

1. Use the Gauss-Jordan elimination method to find the inverse of matrices **A**, **B**, and **C**.
2. Implement the procedure in Python (using NumPy) or any programming language of your choice.
3. Ensure that the code works properly and provides the correct inverse for all three matrices.

---

### Hints:

- Matrix A and B are expected to be invertible.
- Matrix C is a permutation matrix; its inverse is its transpose.
- Check the row operations carefully to avoid errors in calculation.

Good luck!


In [2]:
import numpy as np

def gauss_jordan_inverse(matrix):
    # Augment the matrix with the identity matrix
    n = len(matrix)
    augmented_matrix = np.hstack((matrix, np.eye(n)))

    # Perform Gaussian elimination
    for i in range(n):
        # If the diagonal element is zero, skip to the next row (handle permutation matrices)
        if augmented_matrix[i, i] == 0:
            raise ValueError("Matrix is singular and cannot be inverted.")

        # Make the diagonal element 1
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]

        # Eliminate all other entries in the column
        for j in range(n):
            if i != j:
                augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]

    # The right part of the augmented matrix is the inverse
    return augmented_matrix[:, n:]

# Matrices A, B, and C
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3], [4, 5, 1], [2, 3, 2]])
C = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

# Inverse matrices
A_inv = gauss_jordan_inverse(A)
B_inv = gauss_jordan_inverse(B)

# For matrix C, the inverse is the transpose
C_inv = C.T

# Print the results
print("Inverse of A:")
print(A_inv)
print("\nInverse of B:")
print(B_inv)
print("\nInverse of C:")
print(C_inv)


Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of B:
[[  7.   5. -13.]
 [ -6.  -4.  11.]
 [  2.   1.  -3.]]

Inverse of C:
[[0 0 1]
 [0 1 0]
 [1 0 0]]
